spring:
  application:
    name: dallinday
  profiles:
    active: prod,security
  output:
    ansi:
      enabled: DETECT
  logging:
    level:
      root: INFO
      org.apache: WARN
      org.springframework.orm.jpa: DEBUG